# Generated by Django 2.1.4 on 2018-12-13 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agahi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('discriptation', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='compane_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مسیولیت محدود', 'مسیولیت محدود'), ('سهامی خاص', 'سهامی خاص'), ('سهامی عام', 'سهامی عام'), ('سایر', 'سایر')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=20)),
                ('modir_name', models.CharField(max_length=20)),
                ('id1', models.CharField(max_length=10)),
                ('id_date', models.DateField()),
                ('modirn', models.IntegerField()),
                ('member_n', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('web', models.URLField(blank=True)),
                ('logo_picture', models.FileField(upload_to='static/company_logo')),
                ('rez_picture', models.FileField(upload_to='static/company_rez')),
                ('compane_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compane_type')),
            ],
        ),
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('کامپیوتر', 'کامپیوتر'), ('حسابداری', 'حسابداری'), ('برق', 'برق'), ('ادبیات', 'ادبیات'), ('سایر', 'سایر')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مدیر', 'مدیر'), ('کارمند', 'کارمند'), ('کارگر', 'کارگر'), ('مدرس', 'مدرس')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='job_field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('سابداری', 'حسابداری'), ('برنامه نویسی', 'برنلمه نویسی')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='job_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('نیمه وقت', 'نیمه وقت'), ('تمام وقت', 'تمام وقت'), ('پروژه ای', 'پروژه ای')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='madrak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('زیر دیپلم', 'زیر دیپلم'), ('دیپلم', 'دیپلم'), ('فوق دیپلم', 'فوق دیپلم'), ('لیسانس', 'لیسانس'), ('فوق لیسانس', 'فوق لیسانس'), ('دکترا', 'دکترا')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='marry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مجرد', 'مجرد'), ('متاهل', 'متاهل')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ostan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='shahr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ostan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ostan')),
            ],
        ),
        migrations.CreateModel(
            name='worcker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=20)),
                ('id1', models.CharField(blank=True, max_length=10)),
                ('birthday', models.IntegerField()),
                ('mobile', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11)),
                ('exprience1', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('pay', models.IntegerField()),
                ('pers_pictuare', models.FileField(upload_to='static/user_pers')),
                ('rez_picture', models.FileField(blank=True, null=True, upload_to='static/user_rez')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.education')),
                ('job1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('job_field1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_field')),
                ('job_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_type')),
                ('madrak1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.madrak')),
                ('marry_type1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marry')),
                ('ostan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ostan')),
                ('sex1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sex')),
                ('shahr1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shahr')),
            ],
        ),
        migrations.CreateModel(
            name='worktype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('تولیدی', 'تولیدی'), ('خدماتی', 'خدماتی'), ('بازرگانی', 'بازرگانی'), ('دولتی', 'دولتی')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='job_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_field'),
        ),
        migrations.AddField(
            model_name='company',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_type'),
        ),
        migrations.AddField(
            model_name='company',
            name='ostan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ostan'),
        ),
        migrations.AddField(
            model_name='company',
            name='shahr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shahr'),
        ),
        migrations.AddField(
            model_name='company',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.worktype'),
        ),
        migrations.AddField(
            model_name='agahi',
            name='company1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
