# Generated by Django 2.1.4 on 2018-12-14 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worcker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='worcker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worcker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='worcker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='worcker',
            name='username',
        ),
        migrations.AddField(
            model_name='worcker',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agahi',
            name='company1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='app.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='worcker',
            name='pers_pictuare',
            field=models.FileField(blank=True, null=True, upload_to='static/user_pers'),
        ),
    ]
